name: ProvnZero Release

on:
  push:
    tags:
      - 'v*'  # Supports v1.0.0, v1.1.0-beta.1, etc.

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: Install & Build
        working-directory: ./provnzero-sdk
        run: |
          npm ci
          npm run build
      - name: Publish to NPM
        working-directory: ./provnzero-sdk
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push tag
        uses: docker/build-push-action@v5
        with:
          context: ./provnzero-proxy
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/provnzero-proxy:latest, ${{ secrets.DOCKER_USERNAME }}/provnzero-proxy:${{ github.ref_name }}

  publish-crates-io:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish to crates.io
        working-directory: ./provnzero-proxy
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

  create-github-release:
    needs: [publish-npm, publish-docker, publish-crates-io]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
